export const cspPresets: Record<string, string[]> = {
	localdev: [
		"default-src 'self'",
		"script-src 'self' 'unsafe-inline' 'unsafe-eval' https: http: localhost:* 127.0.0.1:*",
		"style-src 'self' 'unsafe-inline' https: http:",
		"img-src 'self' data: https: http:",
		"font-src 'self' https: data:",
		"connect-src 'self' https: http: ws://localhost:* ws://127.0.0.1:*",
		"object-src 'none'",
		"frame-ancestors 'none'",
		"base-uri 'self'",
	],
	development: [
		"default-src 'self'",
		"script-src 'self' 'unsafe-inline' 'unsafe-eval' https:",
		"style-src 'self' 'unsafe-inline' https:",
		"img-src 'self' data: https:",
		"font-src 'self' https: data:",
		"connect-src 'self' https: ws:",
		"object-src 'none'",
		"frame-ancestors 'none'",
		"base-uri 'self'",
	],
	staging: [
		"default-src 'self'",
		"script-src 'self' 'unsafe-inline' https:",
		"style-src 'self' 'unsafe-inline' https:",
		"img-src 'self' data: https:",
		"font-src 'self' https: data:",
		"connect-src 'self' https: wss:",
		"object-src 'none'",
		"frame-ancestors 'none'",
		"base-uri 'self'",
	],
	production: [
		"default-src 'self'",
		"script-src 'self' https:",
		"style-src 'self' https:",
		"img-src 'self' data: https:",
		"font-src 'self' https: data:",
		"connect-src 'self' https: wss:",
		"object-src 'none'",
		"frame-ancestors 'none'",
		"base-uri 'self'",
	],
};
